site_name: "BEN: Banking Ecosystem Network"
site_url: "https://SUPER-CODERS-itmo.github.io/BEN/"
repo_url: https://github.com/SUPER-CODERS-itmo/BEN
repo_name: SUPER-CODERS-itmo/BEN
edit_uri: edit/main/docs/

# Подключаем кастомные стили (файл должен лежать в docs/stylesheets/extra.css)
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Темная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo # CSS это перекрасит в лайм
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Светлая тема
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    - navigation.path
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
            - src_back
            - src_alice
            - src_sasha
            - src_tests
            - src_tests/tests
            - src_bus_front
            - src_ega_front
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            members_order: alphabetical

nav:
  - Главная: index.md
  - Backend: backend.md
  - Тестирование: tests.md
  - Telegram Bot: tg.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list