name: Dev Branch Check

on:
  push:
    branches:
      - dev_sasha_test
  pull_request:
    branches:
      - main

jobs:
  my-super-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas numpy faker aiogram httpx aiosqlite aiohttp-socks pytest fastapi

      - name: Run tests
        run: |
          python -m unittest discover -s tests -t .
        env:
          PYTHONPATH: "./:./backend"
          BOT_TOKEN: "test-token-stub"