name: Deploy BEN Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      # 1. Основная ветка с конфигами и md-файлами
      - name: Checkout Main
        uses: actions/checkout@v4

      # 2. Выкачиваем все ветки с кодом в разные папки
      - name: Checkout Alice Back
        uses: actions/checkout@v4
        with:
          ref: alice_back
          path: src_alice

      - name: Checkout Sasha Back
        uses: actions/checkout@v4
        with:
          ref: sasha_back
          path: src_sasha

      - name: Checkout Backend (General)
        uses: actions/checkout@v4
        with:
          ref: back
          path: src_back

      - name: Checkout Tests
        uses: actions/checkout@v4
        with:
          ref: tests
          path: src_tests

      - name: Checkout Business Front
        uses: actions/checkout@v4
        with:
          ref: buisness_front
          path: src_bus_front

      - name: Checkout Ega Front
        uses: actions/checkout@v4
        with:
          ref: ega_front
          path: src_ega_front

      # 3. Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 4. Установка зависимостей
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings[python]
          # Обязательно ставим зависимости твоего кода, иначе mkdocstrings не сможет его прочитать
          pip install pandas numpy faker
          # Если есть специфичные либы, добавь их сюда или создай requirements.txt

      # 5. Сборка и деплой
      - name: Build and Deploy
        run: mkdocs gh-deploy --force